[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "durapy"
version = "1.0.0.3"
description = "A modern Python utility library from the Durendal ecosystem."
readme = "docs/README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

authors = [
    { name = "Simon Stordal Amundgård", email = "nomispus@icloud.com" }
]

keywords = [
    "engineering",
    "utilities",
    "python",
    "math",
    "cli",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent"
]

dependencies = [
    "questionary",
    "prompt_toolkit",
    "numpy",
    "sympy",
    "scipy",
    "rich"
]

[project.urls]
Homepage = "https://github.com/draconis-engineering/durapy"
Repository = "https://github.com/draconis-engineering/durapy"
Issues = "https://github.com/draconis-engineering/durapy/issues"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["durapy*"]
